name: Nasjonal Turbase
description: 'Dokumentasjon for Nasjonal Turbase'
cdn: http://cdn.turistforeningen.no
terms: https://docs.google.com/document/d/13aB_C9CGDYYUvfbVgSwjpHnzoUx2uR2NmeEvk7OGnZU/pub
ga_id: UA-45821478-1
encoding: UTF-8

relative_permalinks: false
permalink: /nyheter/:year/:month/:day/:title/
excerpt_separator: <!--more-->
markdown: redcarpet
highlighter: true
timezone: NO

safe: true

gems:
- jekyll-mentions
- jemoji
- jekyll-redirect-from
- jekyll-sitemap

