name: Nasjonal Turbase
description: 'Dokumentasjon for Nasjonal Turbase'
url: http://documentation.nasjonalturbase.no
repo: https://github.com/turistforeningen/www.nasjonalturbase.no
ga_id: UA-45821478-1
encoding: UTF-8

relative_permalinks: false
permalink: /news/:year/:month/:day/:title/
excerpt_separator: <!--more-->
markdown: redcarpet
pygments: true
timezone: NO

safe: true
